artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://foodclassification261106.s3.amazonaws.com/foodclassification.zip
  object_key: foodclassification.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion
  bucket_name: foodclassification261106